version: '3'
services:
  db:
    build: db/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 6
  scraper:
    build: scraper/

    command: scrapy crawl listings
    depends_on:
      db:
        condition: service_healthy
  displayserver:
    build: displayserver/

    command: ./displayserver.py
    ports:
      - 8080:8080

    depends_on:
      db:
        condition: service_healthy
      scraper:
        condition: service_completed_successfully
